### ISSUE TITLE
Couldn't find the password! Please tell it to me and the users. The password in the sql file maybe corrupted.

### ISSUE THREAD

**Issue by N1Mirzo** [thenipunarora/newsportal#1]

**Comment by thenipunarora** [comment]
root

**Comment by N1Mirzo** [comment]
No it is not working!
It is saying wrong password.

**Comment by N1Mirzo** [comment]
You've said the password is Test @12345 and I saw the encoded code as $2y$12$i4LMfeFPQpGSNPTaccIkKuwxAkJ4PhBr3JND7FpXwWFjRvchQn17C .
And now They are incorrect.

**Comment by N1Mirzo** [comment]
**Oh, I found a way to solve this.
I go to the website and make my bycript password.
https://www.browserling.com/tools/bcrypt**

Put the values you want down here:
`INSERT INTO `tbladmin` (`id`, `AdminUserName`, `AdminPassword`, `AdminEmailId`, `Is_Active`, `CreationDate`, `UpdationDate`) VALUES (NULL, 'admin2', 'NOTEHEREISYOURGENERATEDBYCRIPTHASHPASSWORDCODE', 'admin@gmail.com', '1', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000');`

**and the above values:
id: autoincremented(default ide is 2) (you don't need to write it).
AdminUserName: Admin2
AdminPassword is the password you wrote to generate its bycript hashcode.
AdminEmailId: admin@gmail.com
Is_Active: 1(True or yes active if 0 false or not active )
CreationDate: autotimestamp (the date you created)(you don't need to write it).
UpdationDate: autotimestamo (the date you updated)(you don't need to write it).**

So if you love the answer just you know what to do!
